# Site settings
title: Suraj Thite
email: suraj.thite@colorado.edu
description: Embedded Firmware Design Engineer. # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://surajthite.github.io/" # the base hostname & protocol for your site
twitter_username: surajthit3
github_username:  surajthite

# Build settings
markdown: kramdown

#advantage - globally accessible
# for e.g. site.title , site.email, site.url etc using Liquid template can be used anywhere